### PR TITLE
Improved sk_sk translation.

### PR DESCRIPTION
**Pull request by jasomtubratu**
Some small grammatical typos

### CODE REVIEW

**Comment by BananaPuncher714** [comment]
Thanks! I'll add this to the next update! What's your spigot username?

**Comment by jasomtubratu** [comment]
I am the original author of this translation. When I translated it I made some minor mistakes. Because I went to use that translation and I saw it.

It could still be understood but grammatical errors

**Comment by BananaPuncher714** [comment]
Ok, thanks for your improvements!!

**Comment by jasomtubratu** [comment]
No problem I wrote this as a 13/14 year old 😂 If I find anything else I'll be sure to get back to you. 

Have a great Day! 🤭

**Pull request merged**
